name: Sistema de Ventas Automatizado
on:
  workflow_dispatch:

jobs:
  proceso_completo:
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizando Archivos
        uses: actions/checkout@v3

      - name: Configurando Entorno Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Ejecutando Escaneo Masivo (1.200 Leads)
        run: python propuestas.py

      - name: Ejecutando Sistema de Cobros
        run: python recaudador.py
